### ISSUE TITLE
The title cheated me to click the repo.  =_=|

### ISSUE THREAD

**Issue by gapry** [eugenelet/Neural-Network-for-Classification#1]

**Comment by eugenelet** [comment]
Was about to upload, adding comments... haha

**Comment by gapry** [comment]
I guess it's a matlab homework

**Comment by eugenelet** [comment]
Nah, I'm using Python for this, due to its extensibility.

**Comment by gapry** [comment]
Woo, I guess it's ML Homework

**Comment by eugenelet** [comment]
Bingo! Documenting all my work. Haha

**Comment by gapry** [comment]
We use Github issue as IRC Channel.  So stupid, Haha XDDD

**Comment by eugenelet** [comment]
Nobody will notice xDD

**Comment by eugenelet** [comment]
This is like the 2nd page of Google search results

**Comment by gapry** [comment]
Good point, Nobody will notice  XDD
